# Generated by Django 2.0.10 on 2019-02-12 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='id_demand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Demand', verbose_name='Номер заявки: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='name_product',
            field=models.CharField(max_length=50, verbose_name='Наименование:'),
        ),
    ]
